/* unity_entrypoints.h -- AUTO-GENERATED by extract_entrypoints.py
 * Link-time offsets for THIS EXACT libunity.so. Re-run if the game updates.
 * Runtime address = unity_mod.load_virtbase + offset. */
#ifndef UNITY_ENTRYPOINTS_H
#define UNITY_ENTRYPOINTS_H

#include <stdint.h>
#include "so_util.h"

#define OFF_JNI_OnLoad                      0x335130

/* table of 28 @ 0x101a858 */
#define OFF_initJni                             0x33453c   /* (Landroid/content/Context;)V */
#define OFF_nativeDone                          0x3345a4   /* ()Z */
#define OFF_nativePause                         0x334624   /* ()Z */
#define OFF_nativeRecreateGfxState              0x3347a0   /* (ILandroid/view/Surface;)V */
#define OFF_nativeSendSurfaceChangedEvent       0x334804   /* ()V */
#define OFF_nativeRender                        0x334850   /* ()Z */
#define OFF_nativeResume                        0x33467c   /* ()V */
#define OFF_nativeLowMemory                     0x3346b8   /* ()V */
#define OFF_nativeApplicationUnload             0x3346f4   /* ()V */
#define OFF_nativeFocusChanged                  0x334738   /* (Z)V */
#define OFF_nativeSetInputArea                  0x334a28   /* (IIII)V */
#define OFF_nativeSetKeyboardIsVisible          0x334a9c   /* (Z)V */
#define OFF_nativeSetInputString                0x334af0   /* (Ljava/lang/String;)V */
#define OFF_nativeSetInputSelection             0x334ba0   /* (II)V */
#define OFF_nativeSoftInputClosed               0x334cc0   /* ()V */
#define OFF_nativeSoftInputCanceled             0x334bfc   /* ()V */
#define OFF_nativeReportKeyboardConfigChanged   0x334c84   /* ()V */
#define OFF_nativeSoftInputLostFocus            0x334c40   /* ()V */
#define OFF_nativeInjectEvent                   0x3348a4   /* (Landroid/view/InputEvent;)Z */
#define OFF_nativeUnitySendMessage              0x334d04   /* (Ljava/lang/String;Ljava/lang/String;[B)V */
#define OFF_nativeIsAutorotationOn              0x334ea8   /* ()Z */
#define OFF_nativeMuteMasterAudio               0x334f04   /* (Z)V */
#define OFF_nativeRestartActivityIndicator      0x334f5c   /* ()V */
#define OFF_nativeSetLaunchURL                  0x334f98   /* (Ljava/lang/String;)V */
#define OFF_nativeOrientationChanged            0x3350dc   /* (II)V */
#define OFF_nOnChoreographer                    0x8483d0   /* (JJ)V */
#define OFF_nOnRefreshPeriodChanged             0x84aa34   /* (JJJJ)V */
#define OFF_nSetSupportedRefreshPeriods         0x84a854   /* (J[J[I)V */

/* table of 4 @ 0x101a5b0 */
#define OFF_initCamera2Jni                      0x305018   /* ()V */
#define OFF_deinitCamera2Jni                    0x305064   /* ()V */
#define OFF_nativeFrameReady                    0x30beb8   /* (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;III)V */
#define OFF_nativeSurfaceTextureReady           0x30bd74   /* (Ljava/lang/Object;)V */

/* table of 4 @ 0x101a7d8 */
#define OFF_onAudioVolumeChanged                0x331024   /* (I)V */
#define OFF_initializeARCore                    0x333c98   /* (Landroid/app/Activity;)V */
#define OFF_pauseARCore                         0x333cfc   /* ()V */
#define OFF_resumeARCore                        0x333d44   /* ()V */

/* table of 3 @ 0x101ac40 */
#define OFF_nativeProxyInvoke                   0xef888   /* (JLjava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object; */
#define OFF_nativeProxyFinalize                 0xef9c0   /* (J)V */
#define OFF_nativeProxyLogJNIInvokeException    0xefa08   /* (J)V */

/* table of 3 @ 0x10253d8 */
#define OFF_fmodGetInfo                         0x9a9898   /* (I)I */
#define OFF_fmodProcess                         0x9a9960   /* (Ljava/nio/ByteBuffer;)I */
#define OFF_fmodProcessMicData                  0x9a99ec   /* (Ljava/nio/ByteBuffer;I)I */

/* table of 2 @ 0xffb0d8 */

/* table of 2 @ 0x101a790 */
#define OFF_initHFPStatusJni                    0x32ea00   /* ()V */
#define OFF_deinitHFPStatusJni                  0x32ea4c   /* ()V */

/* table of 1 @ 0xffaed8 */

/* table of 1 @ 0x101a6d0 */
#define OFF_nativeUpdateOrientationLockState    0x30eaac   /* (I)V */

/* table of 1 @ 0x101a700 */
#define OFF_nativeStatusQueryResult             0x31a024   /* (Ljava/lang/String;II)V */

#define OFF_nativeSendSurfaceChanged      OFF_nativeSendSurfaceChangedEvent

typedef void     (*fn_initJni)(void*,void*,void*);
typedef void     (*fn_gfxstate)(void*,void*,int32_t,void*);
typedef void     (*fn_v)(void*,void*);
typedef uint8_t  (*fn_z)(void*,void*);
typedef void     (*fn_vz)(void*,void*,int32_t);
typedef uint8_t  (*fn_inject)(void*,void*,void*,int32_t);
typedef void     (*fn_orient)(void*,void*,int32_t,int32_t);

#define UNITY_RESOLVE(mod, off) ((void*)((uintptr_t)(mod).load_virtbase + (off)))

#endif /* UNITY_ENTRYPOINTS_H */
